// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqbADXkTNfZz1o-lD9-e8WEif7NPX1zUw',
    appId: '1:82369512623:web:4db3b532b00565186f005a',
    messagingSenderId: '82369512623',
    projectId: 'crested-photon-435918-h1',
    authDomain: 'crested-photon-435918-h1.firebaseapp.com',
    storageBucket: 'crested-photon-435918-h1.firebasestorage.app',
    measurementId: 'G-64CW2P076D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgq-Nbs9suFmk61o3rsLVxdy16heW9QM',
    appId: '1:82369512623:android:286c1a6fa8dade1e6f005a',
    messagingSenderId: '82369512623',
    projectId: 'crested-photon-435918-h1',
    storageBucket: 'crested-photon-435918-h1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtoITmWa5VzGcOH5NQaJ567v_WedTec8',
    appId: '1:82369512623:ios:491ef50e6eec4b506f005a',
    messagingSenderId: '82369512623',
    projectId: 'crested-photon-435918-h1',
    storageBucket: 'crested-photon-435918-h1.firebasestorage.app',
    androidClientId: '82369512623-6b0gqiqmvse41g6l2sm6ufkfsvtg6t8h.apps.googleusercontent.com',
    iosClientId: '82369512623-rn4e664numvs4fhmnpi15b8rhvlrnvvv.apps.googleusercontent.com',
    iosBundleId: 'com.sangak.app',
  );
}
